/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class statistics_Chi2 */

#ifndef _Included_statistics_Chi2
#define _Included_statistics_Chi2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     statistics_Chi2
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_statistics_Chi2_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     statistics_Chi2
 * Method:    calculate0
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_statistics_Chi2_calculate0
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     statistics_Chi2
 * Method:    calculate
 * Signature: ([Ljava/lang/Double;)V
 */
JNIEXPORT void JNICALL Java_statistics_Chi2_calculate___3Ljava_lang_Double_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     statistics_Chi2
 * Method:    calculate
 * Signature: ()[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_statistics_Chi2_calculate__
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
